/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsIndexRouteImport } from './routes/docs.index'
import { Route as DocsComponentsTooltipRouteImport } from './routes/docs.components.tooltip'
import { Route as DocsComponentsTextareaRouteImport } from './routes/docs.components.textarea'
import { Route as DocsComponentsTextRouteImport } from './routes/docs.components.text'
import { Route as DocsComponentsTagRouteImport } from './routes/docs.components.tag'
import { Route as DocsComponentsSwitchRouteImport } from './routes/docs.components.switch'
import { Route as DocsComponentsSeparatorRouteImport } from './routes/docs.components.separator'
import { Route as DocsComponentsRatingRouteImport } from './routes/docs.components.rating'
import { Route as DocsComponentsRadioRouteImport } from './routes/docs.components.radio'
import { Route as DocsComponentsPinInputRouteImport } from './routes/docs.components.pin-input'
import { Route as DocsComponentsPasswordInputRouteImport } from './routes/docs.components.password-input'
import { Route as DocsComponentsMenuRouteImport } from './routes/docs.components.menu'
import { Route as DocsComponentsInputRouteImport } from './routes/docs.components.input'
import { Route as DocsComponentsHighlightRouteImport } from './routes/docs.components.highlight'
import { Route as DocsComponentsHeadingRouteImport } from './routes/docs.components.heading'
import { Route as DocsComponentsFieldRouteImport } from './routes/docs.components.field'
import { Route as DocsComponentsDatePickerRouteImport } from './routes/docs.components.date-picker'
import { Route as DocsComponentsCodeBlockRouteImport } from './routes/docs.components.code-block'
import { Route as DocsComponentsClipboardRouteImport } from './routes/docs.components.clipboard'
import { Route as DocsComponentsCheckboxCardRouteImport } from './routes/docs.components.checkbox-card'
import { Route as DocsComponentsCheckboxRouteImport } from './routes/docs.components.checkbox'
import { Route as DocsComponentsCardRouteImport } from './routes/docs.components.card'
import { Route as DocsComponentsButtonRouteImport } from './routes/docs.components.button'
import { Route as DocsComponentsAvatarRouteImport } from './routes/docs.components.avatar'
import { Route as DocsComponentsAlertRouteImport } from './routes/docs.components.alert'
import { Route as DocsComponentsAccordionRouteImport } from './routes/docs.components.accordion'
import { Route as DocsChartsAreaChartRouteImport } from './routes/docs.charts.area-chart'
import { Route as DocsFirstStepsIntroductionIndexRouteImport } from './routes/docs.first-steps.introduction.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsComponentsTooltipRoute = DocsComponentsTooltipRouteImport.update({
  id: '/docs/components/tooltip',
  path: '/docs/components/tooltip',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsComponentsTextareaRoute = DocsComponentsTextareaRouteImport.update({
  id: '/docs/components/textarea',
  path: '/docs/components/textarea',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsComponentsTextRoute = DocsComponentsTextRouteImport.update({
  id: '/docs/components/text',
  path: '/docs/components/text',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsComponentsTagRoute = DocsComponentsTagRouteImport.update({
  id: '/docs/components/tag',
  path: '/docs/components/tag',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsComponentsSwitchRoute = DocsComponentsSwitchRouteImport.update({
  id: '/docs/components/switch',
  path: '/docs/components/switch',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsComponentsSeparatorRoute = DocsComponentsSeparatorRouteImport.update({
  id: '/docs/components/separator',
  path: '/docs/components/separator',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsComponentsRatingRoute = DocsComponentsRatingRouteImport.update({
  id: '/docs/components/rating',
  path: '/docs/components/rating',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsComponentsRadioRoute = DocsComponentsRadioRouteImport.update({
  id: '/docs/components/radio',
  path: '/docs/components/radio',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsComponentsPinInputRoute = DocsComponentsPinInputRouteImport.update({
  id: '/docs/components/pin-input',
  path: '/docs/components/pin-input',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsComponentsPasswordInputRoute =
  DocsComponentsPasswordInputRouteImport.update({
    id: '/docs/components/password-input',
    path: '/docs/components/password-input',
    getParentRoute: () => rootRouteImport,
  } as any)
const DocsComponentsMenuRoute = DocsComponentsMenuRouteImport.update({
  id: '/docs/components/menu',
  path: '/docs/components/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsComponentsInputRoute = DocsComponentsInputRouteImport.update({
  id: '/docs/components/input',
  path: '/docs/components/input',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsComponentsHighlightRoute = DocsComponentsHighlightRouteImport.update({
  id: '/docs/components/highlight',
  path: '/docs/components/highlight',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsComponentsHeadingRoute = DocsComponentsHeadingRouteImport.update({
  id: '/docs/components/heading',
  path: '/docs/components/heading',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsComponentsFieldRoute = DocsComponentsFieldRouteImport.update({
  id: '/docs/components/field',
  path: '/docs/components/field',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsComponentsDatePickerRoute =
  DocsComponentsDatePickerRouteImport.update({
    id: '/docs/components/date-picker',
    path: '/docs/components/date-picker',
    getParentRoute: () => rootRouteImport,
  } as any)
const DocsComponentsCodeBlockRoute = DocsComponentsCodeBlockRouteImport.update({
  id: '/docs/components/code-block',
  path: '/docs/components/code-block',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsComponentsClipboardRoute = DocsComponentsClipboardRouteImport.update({
  id: '/docs/components/clipboard',
  path: '/docs/components/clipboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsComponentsCheckboxCardRoute =
  DocsComponentsCheckboxCardRouteImport.update({
    id: '/docs/components/checkbox-card',
    path: '/docs/components/checkbox-card',
    getParentRoute: () => rootRouteImport,
  } as any)
const DocsComponentsCheckboxRoute = DocsComponentsCheckboxRouteImport.update({
  id: '/docs/components/checkbox',
  path: '/docs/components/checkbox',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsComponentsCardRoute = DocsComponentsCardRouteImport.update({
  id: '/docs/components/card',
  path: '/docs/components/card',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsComponentsButtonRoute = DocsComponentsButtonRouteImport.update({
  id: '/docs/components/button',
  path: '/docs/components/button',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsComponentsAvatarRoute = DocsComponentsAvatarRouteImport.update({
  id: '/docs/components/avatar',
  path: '/docs/components/avatar',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsComponentsAlertRoute = DocsComponentsAlertRouteImport.update({
  id: '/docs/components/alert',
  path: '/docs/components/alert',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsComponentsAccordionRoute = DocsComponentsAccordionRouteImport.update({
  id: '/docs/components/accordion',
  path: '/docs/components/accordion',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsChartsAreaChartRoute = DocsChartsAreaChartRouteImport.update({
  id: '/docs/charts/area-chart',
  path: '/docs/charts/area-chart',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsFirstStepsIntroductionIndexRoute =
  DocsFirstStepsIntroductionIndexRouteImport.update({
    id: '/docs/first-steps/introduction/',
    path: '/docs/first-steps/introduction/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof DocsIndexRoute
  '/docs/charts/area-chart': typeof DocsChartsAreaChartRoute
  '/docs/components/accordion': typeof DocsComponentsAccordionRoute
  '/docs/components/alert': typeof DocsComponentsAlertRoute
  '/docs/components/avatar': typeof DocsComponentsAvatarRoute
  '/docs/components/button': typeof DocsComponentsButtonRoute
  '/docs/components/card': typeof DocsComponentsCardRoute
  '/docs/components/checkbox': typeof DocsComponentsCheckboxRoute
  '/docs/components/checkbox-card': typeof DocsComponentsCheckboxCardRoute
  '/docs/components/clipboard': typeof DocsComponentsClipboardRoute
  '/docs/components/code-block': typeof DocsComponentsCodeBlockRoute
  '/docs/components/date-picker': typeof DocsComponentsDatePickerRoute
  '/docs/components/field': typeof DocsComponentsFieldRoute
  '/docs/components/heading': typeof DocsComponentsHeadingRoute
  '/docs/components/highlight': typeof DocsComponentsHighlightRoute
  '/docs/components/input': typeof DocsComponentsInputRoute
  '/docs/components/menu': typeof DocsComponentsMenuRoute
  '/docs/components/password-input': typeof DocsComponentsPasswordInputRoute
  '/docs/components/pin-input': typeof DocsComponentsPinInputRoute
  '/docs/components/radio': typeof DocsComponentsRadioRoute
  '/docs/components/rating': typeof DocsComponentsRatingRoute
  '/docs/components/separator': typeof DocsComponentsSeparatorRoute
  '/docs/components/switch': typeof DocsComponentsSwitchRoute
  '/docs/components/tag': typeof DocsComponentsTagRoute
  '/docs/components/text': typeof DocsComponentsTextRoute
  '/docs/components/textarea': typeof DocsComponentsTextareaRoute
  '/docs/components/tooltip': typeof DocsComponentsTooltipRoute
  '/docs/first-steps/introduction': typeof DocsFirstStepsIntroductionIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs': typeof DocsIndexRoute
  '/docs/charts/area-chart': typeof DocsChartsAreaChartRoute
  '/docs/components/accordion': typeof DocsComponentsAccordionRoute
  '/docs/components/alert': typeof DocsComponentsAlertRoute
  '/docs/components/avatar': typeof DocsComponentsAvatarRoute
  '/docs/components/button': typeof DocsComponentsButtonRoute
  '/docs/components/card': typeof DocsComponentsCardRoute
  '/docs/components/checkbox': typeof DocsComponentsCheckboxRoute
  '/docs/components/checkbox-card': typeof DocsComponentsCheckboxCardRoute
  '/docs/components/clipboard': typeof DocsComponentsClipboardRoute
  '/docs/components/code-block': typeof DocsComponentsCodeBlockRoute
  '/docs/components/date-picker': typeof DocsComponentsDatePickerRoute
  '/docs/components/field': typeof DocsComponentsFieldRoute
  '/docs/components/heading': typeof DocsComponentsHeadingRoute
  '/docs/components/highlight': typeof DocsComponentsHighlightRoute
  '/docs/components/input': typeof DocsComponentsInputRoute
  '/docs/components/menu': typeof DocsComponentsMenuRoute
  '/docs/components/password-input': typeof DocsComponentsPasswordInputRoute
  '/docs/components/pin-input': typeof DocsComponentsPinInputRoute
  '/docs/components/radio': typeof DocsComponentsRadioRoute
  '/docs/components/rating': typeof DocsComponentsRatingRoute
  '/docs/components/separator': typeof DocsComponentsSeparatorRoute
  '/docs/components/switch': typeof DocsComponentsSwitchRoute
  '/docs/components/tag': typeof DocsComponentsTagRoute
  '/docs/components/text': typeof DocsComponentsTextRoute
  '/docs/components/textarea': typeof DocsComponentsTextareaRoute
  '/docs/components/tooltip': typeof DocsComponentsTooltipRoute
  '/docs/first-steps/introduction': typeof DocsFirstStepsIntroductionIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docs/': typeof DocsIndexRoute
  '/docs/charts/area-chart': typeof DocsChartsAreaChartRoute
  '/docs/components/accordion': typeof DocsComponentsAccordionRoute
  '/docs/components/alert': typeof DocsComponentsAlertRoute
  '/docs/components/avatar': typeof DocsComponentsAvatarRoute
  '/docs/components/button': typeof DocsComponentsButtonRoute
  '/docs/components/card': typeof DocsComponentsCardRoute
  '/docs/components/checkbox': typeof DocsComponentsCheckboxRoute
  '/docs/components/checkbox-card': typeof DocsComponentsCheckboxCardRoute
  '/docs/components/clipboard': typeof DocsComponentsClipboardRoute
  '/docs/components/code-block': typeof DocsComponentsCodeBlockRoute
  '/docs/components/date-picker': typeof DocsComponentsDatePickerRoute
  '/docs/components/field': typeof DocsComponentsFieldRoute
  '/docs/components/heading': typeof DocsComponentsHeadingRoute
  '/docs/components/highlight': typeof DocsComponentsHighlightRoute
  '/docs/components/input': typeof DocsComponentsInputRoute
  '/docs/components/menu': typeof DocsComponentsMenuRoute
  '/docs/components/password-input': typeof DocsComponentsPasswordInputRoute
  '/docs/components/pin-input': typeof DocsComponentsPinInputRoute
  '/docs/components/radio': typeof DocsComponentsRadioRoute
  '/docs/components/rating': typeof DocsComponentsRatingRoute
  '/docs/components/separator': typeof DocsComponentsSeparatorRoute
  '/docs/components/switch': typeof DocsComponentsSwitchRoute
  '/docs/components/tag': typeof DocsComponentsTagRoute
  '/docs/components/text': typeof DocsComponentsTextRoute
  '/docs/components/textarea': typeof DocsComponentsTextareaRoute
  '/docs/components/tooltip': typeof DocsComponentsTooltipRoute
  '/docs/first-steps/introduction/': typeof DocsFirstStepsIntroductionIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs'
    | '/docs/charts/area-chart'
    | '/docs/components/accordion'
    | '/docs/components/alert'
    | '/docs/components/avatar'
    | '/docs/components/button'
    | '/docs/components/card'
    | '/docs/components/checkbox'
    | '/docs/components/checkbox-card'
    | '/docs/components/clipboard'
    | '/docs/components/code-block'
    | '/docs/components/date-picker'
    | '/docs/components/field'
    | '/docs/components/heading'
    | '/docs/components/highlight'
    | '/docs/components/input'
    | '/docs/components/menu'
    | '/docs/components/password-input'
    | '/docs/components/pin-input'
    | '/docs/components/radio'
    | '/docs/components/rating'
    | '/docs/components/separator'
    | '/docs/components/switch'
    | '/docs/components/tag'
    | '/docs/components/text'
    | '/docs/components/textarea'
    | '/docs/components/tooltip'
    | '/docs/first-steps/introduction'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/docs'
    | '/docs/charts/area-chart'
    | '/docs/components/accordion'
    | '/docs/components/alert'
    | '/docs/components/avatar'
    | '/docs/components/button'
    | '/docs/components/card'
    | '/docs/components/checkbox'
    | '/docs/components/checkbox-card'
    | '/docs/components/clipboard'
    | '/docs/components/code-block'
    | '/docs/components/date-picker'
    | '/docs/components/field'
    | '/docs/components/heading'
    | '/docs/components/highlight'
    | '/docs/components/input'
    | '/docs/components/menu'
    | '/docs/components/password-input'
    | '/docs/components/pin-input'
    | '/docs/components/radio'
    | '/docs/components/rating'
    | '/docs/components/separator'
    | '/docs/components/switch'
    | '/docs/components/tag'
    | '/docs/components/text'
    | '/docs/components/textarea'
    | '/docs/components/tooltip'
    | '/docs/first-steps/introduction'
  id:
    | '__root__'
    | '/'
    | '/docs/'
    | '/docs/charts/area-chart'
    | '/docs/components/accordion'
    | '/docs/components/alert'
    | '/docs/components/avatar'
    | '/docs/components/button'
    | '/docs/components/card'
    | '/docs/components/checkbox'
    | '/docs/components/checkbox-card'
    | '/docs/components/clipboard'
    | '/docs/components/code-block'
    | '/docs/components/date-picker'
    | '/docs/components/field'
    | '/docs/components/heading'
    | '/docs/components/highlight'
    | '/docs/components/input'
    | '/docs/components/menu'
    | '/docs/components/password-input'
    | '/docs/components/pin-input'
    | '/docs/components/radio'
    | '/docs/components/rating'
    | '/docs/components/separator'
    | '/docs/components/switch'
    | '/docs/components/tag'
    | '/docs/components/text'
    | '/docs/components/textarea'
    | '/docs/components/tooltip'
    | '/docs/first-steps/introduction/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsIndexRoute: typeof DocsIndexRoute
  DocsChartsAreaChartRoute: typeof DocsChartsAreaChartRoute
  DocsComponentsAccordionRoute: typeof DocsComponentsAccordionRoute
  DocsComponentsAlertRoute: typeof DocsComponentsAlertRoute
  DocsComponentsAvatarRoute: typeof DocsComponentsAvatarRoute
  DocsComponentsButtonRoute: typeof DocsComponentsButtonRoute
  DocsComponentsCardRoute: typeof DocsComponentsCardRoute
  DocsComponentsCheckboxRoute: typeof DocsComponentsCheckboxRoute
  DocsComponentsCheckboxCardRoute: typeof DocsComponentsCheckboxCardRoute
  DocsComponentsClipboardRoute: typeof DocsComponentsClipboardRoute
  DocsComponentsCodeBlockRoute: typeof DocsComponentsCodeBlockRoute
  DocsComponentsDatePickerRoute: typeof DocsComponentsDatePickerRoute
  DocsComponentsFieldRoute: typeof DocsComponentsFieldRoute
  DocsComponentsHeadingRoute: typeof DocsComponentsHeadingRoute
  DocsComponentsHighlightRoute: typeof DocsComponentsHighlightRoute
  DocsComponentsInputRoute: typeof DocsComponentsInputRoute
  DocsComponentsMenuRoute: typeof DocsComponentsMenuRoute
  DocsComponentsPasswordInputRoute: typeof DocsComponentsPasswordInputRoute
  DocsComponentsPinInputRoute: typeof DocsComponentsPinInputRoute
  DocsComponentsRadioRoute: typeof DocsComponentsRadioRoute
  DocsComponentsRatingRoute: typeof DocsComponentsRatingRoute
  DocsComponentsSeparatorRoute: typeof DocsComponentsSeparatorRoute
  DocsComponentsSwitchRoute: typeof DocsComponentsSwitchRoute
  DocsComponentsTagRoute: typeof DocsComponentsTagRoute
  DocsComponentsTextRoute: typeof DocsComponentsTextRoute
  DocsComponentsTextareaRoute: typeof DocsComponentsTextareaRoute
  DocsComponentsTooltipRoute: typeof DocsComponentsTooltipRoute
  DocsFirstStepsIntroductionIndexRoute: typeof DocsFirstStepsIntroductionIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/components/tooltip': {
      id: '/docs/components/tooltip'
      path: '/docs/components/tooltip'
      fullPath: '/docs/components/tooltip'
      preLoaderRoute: typeof DocsComponentsTooltipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/components/textarea': {
      id: '/docs/components/textarea'
      path: '/docs/components/textarea'
      fullPath: '/docs/components/textarea'
      preLoaderRoute: typeof DocsComponentsTextareaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/components/text': {
      id: '/docs/components/text'
      path: '/docs/components/text'
      fullPath: '/docs/components/text'
      preLoaderRoute: typeof DocsComponentsTextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/components/tag': {
      id: '/docs/components/tag'
      path: '/docs/components/tag'
      fullPath: '/docs/components/tag'
      preLoaderRoute: typeof DocsComponentsTagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/components/switch': {
      id: '/docs/components/switch'
      path: '/docs/components/switch'
      fullPath: '/docs/components/switch'
      preLoaderRoute: typeof DocsComponentsSwitchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/components/separator': {
      id: '/docs/components/separator'
      path: '/docs/components/separator'
      fullPath: '/docs/components/separator'
      preLoaderRoute: typeof DocsComponentsSeparatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/components/rating': {
      id: '/docs/components/rating'
      path: '/docs/components/rating'
      fullPath: '/docs/components/rating'
      preLoaderRoute: typeof DocsComponentsRatingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/components/radio': {
      id: '/docs/components/radio'
      path: '/docs/components/radio'
      fullPath: '/docs/components/radio'
      preLoaderRoute: typeof DocsComponentsRadioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/components/pin-input': {
      id: '/docs/components/pin-input'
      path: '/docs/components/pin-input'
      fullPath: '/docs/components/pin-input'
      preLoaderRoute: typeof DocsComponentsPinInputRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/components/password-input': {
      id: '/docs/components/password-input'
      path: '/docs/components/password-input'
      fullPath: '/docs/components/password-input'
      preLoaderRoute: typeof DocsComponentsPasswordInputRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/components/menu': {
      id: '/docs/components/menu'
      path: '/docs/components/menu'
      fullPath: '/docs/components/menu'
      preLoaderRoute: typeof DocsComponentsMenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/components/input': {
      id: '/docs/components/input'
      path: '/docs/components/input'
      fullPath: '/docs/components/input'
      preLoaderRoute: typeof DocsComponentsInputRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/components/highlight': {
      id: '/docs/components/highlight'
      path: '/docs/components/highlight'
      fullPath: '/docs/components/highlight'
      preLoaderRoute: typeof DocsComponentsHighlightRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/components/heading': {
      id: '/docs/components/heading'
      path: '/docs/components/heading'
      fullPath: '/docs/components/heading'
      preLoaderRoute: typeof DocsComponentsHeadingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/components/field': {
      id: '/docs/components/field'
      path: '/docs/components/field'
      fullPath: '/docs/components/field'
      preLoaderRoute: typeof DocsComponentsFieldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/components/date-picker': {
      id: '/docs/components/date-picker'
      path: '/docs/components/date-picker'
      fullPath: '/docs/components/date-picker'
      preLoaderRoute: typeof DocsComponentsDatePickerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/components/code-block': {
      id: '/docs/components/code-block'
      path: '/docs/components/code-block'
      fullPath: '/docs/components/code-block'
      preLoaderRoute: typeof DocsComponentsCodeBlockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/components/clipboard': {
      id: '/docs/components/clipboard'
      path: '/docs/components/clipboard'
      fullPath: '/docs/components/clipboard'
      preLoaderRoute: typeof DocsComponentsClipboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/components/checkbox-card': {
      id: '/docs/components/checkbox-card'
      path: '/docs/components/checkbox-card'
      fullPath: '/docs/components/checkbox-card'
      preLoaderRoute: typeof DocsComponentsCheckboxCardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/components/checkbox': {
      id: '/docs/components/checkbox'
      path: '/docs/components/checkbox'
      fullPath: '/docs/components/checkbox'
      preLoaderRoute: typeof DocsComponentsCheckboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/components/card': {
      id: '/docs/components/card'
      path: '/docs/components/card'
      fullPath: '/docs/components/card'
      preLoaderRoute: typeof DocsComponentsCardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/components/button': {
      id: '/docs/components/button'
      path: '/docs/components/button'
      fullPath: '/docs/components/button'
      preLoaderRoute: typeof DocsComponentsButtonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/components/avatar': {
      id: '/docs/components/avatar'
      path: '/docs/components/avatar'
      fullPath: '/docs/components/avatar'
      preLoaderRoute: typeof DocsComponentsAvatarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/components/alert': {
      id: '/docs/components/alert'
      path: '/docs/components/alert'
      fullPath: '/docs/components/alert'
      preLoaderRoute: typeof DocsComponentsAlertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/components/accordion': {
      id: '/docs/components/accordion'
      path: '/docs/components/accordion'
      fullPath: '/docs/components/accordion'
      preLoaderRoute: typeof DocsComponentsAccordionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/charts/area-chart': {
      id: '/docs/charts/area-chart'
      path: '/docs/charts/area-chart'
      fullPath: '/docs/charts/area-chart'
      preLoaderRoute: typeof DocsChartsAreaChartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/first-steps/introduction/': {
      id: '/docs/first-steps/introduction/'
      path: '/docs/first-steps/introduction'
      fullPath: '/docs/first-steps/introduction'
      preLoaderRoute: typeof DocsFirstStepsIntroductionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsIndexRoute: DocsIndexRoute,
  DocsChartsAreaChartRoute: DocsChartsAreaChartRoute,
  DocsComponentsAccordionRoute: DocsComponentsAccordionRoute,
  DocsComponentsAlertRoute: DocsComponentsAlertRoute,
  DocsComponentsAvatarRoute: DocsComponentsAvatarRoute,
  DocsComponentsButtonRoute: DocsComponentsButtonRoute,
  DocsComponentsCardRoute: DocsComponentsCardRoute,
  DocsComponentsCheckboxRoute: DocsComponentsCheckboxRoute,
  DocsComponentsCheckboxCardRoute: DocsComponentsCheckboxCardRoute,
  DocsComponentsClipboardRoute: DocsComponentsClipboardRoute,
  DocsComponentsCodeBlockRoute: DocsComponentsCodeBlockRoute,
  DocsComponentsDatePickerRoute: DocsComponentsDatePickerRoute,
  DocsComponentsFieldRoute: DocsComponentsFieldRoute,
  DocsComponentsHeadingRoute: DocsComponentsHeadingRoute,
  DocsComponentsHighlightRoute: DocsComponentsHighlightRoute,
  DocsComponentsInputRoute: DocsComponentsInputRoute,
  DocsComponentsMenuRoute: DocsComponentsMenuRoute,
  DocsComponentsPasswordInputRoute: DocsComponentsPasswordInputRoute,
  DocsComponentsPinInputRoute: DocsComponentsPinInputRoute,
  DocsComponentsRadioRoute: DocsComponentsRadioRoute,
  DocsComponentsRatingRoute: DocsComponentsRatingRoute,
  DocsComponentsSeparatorRoute: DocsComponentsSeparatorRoute,
  DocsComponentsSwitchRoute: DocsComponentsSwitchRoute,
  DocsComponentsTagRoute: DocsComponentsTagRoute,
  DocsComponentsTextRoute: DocsComponentsTextRoute,
  DocsComponentsTextareaRoute: DocsComponentsTextareaRoute,
  DocsComponentsTooltipRoute: DocsComponentsTooltipRoute,
  DocsFirstStepsIntroductionIndexRoute: DocsFirstStepsIntroductionIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
